/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CuentaRouteImport } from './routes/cuenta'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as CategoriaCategoriaRouteImport } from './routes/categoria.$categoria'
import { Route as NegocioIdRouteImport } from './routes/negocio.$id'
import { Route as PuebloPuebloRouteImport } from './routes/pueblo.$pueblo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentaRoute = CuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaCategoriaRoute = CategoriaCategoriaRouteImport.update({
  id: '/categoria/$categoria',
  path: '/categoria/$categoria',
  getParentRoute: () => rootRouteImport,
} as any)
const NegocioIdRoute = NegocioIdRouteImport.update({
  id: '/negocio/$id',
  path: '/negocio/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PuebloPuebloRoute = PuebloPuebloRouteImport.update({
  id: '/pueblo/$pueblo',
  path: '/pueblo/$pueblo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cuenta': typeof CuentaRoute
  '/terminos': typeof TerminosRoute
  '/categoria/$categoria': typeof CategoriaCategoriaRoute
  '/negocio/$id': typeof NegocioIdRoute
  '/pueblo/$pueblo': typeof PuebloPuebloRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cuenta': typeof CuentaRoute
  '/terminos': typeof TerminosRoute
  '/categoria/$categoria': typeof CategoriaCategoriaRoute
  '/negocio/$id': typeof NegocioIdRoute
  '/pueblo/$pueblo': typeof PuebloPuebloRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cuenta': typeof CuentaRoute
  '/terminos': typeof TerminosRoute
  '/categoria/$categoria': typeof CategoriaCategoriaRoute
  '/negocio/$id': typeof NegocioIdRoute
  '/pueblo/$pueblo': typeof PuebloPuebloRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cuenta'
    | '/terminos'
    | '/categoria/$categoria'
    | '/negocio/$id'
    | '/pueblo/$pueblo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cuenta'
    | '/terminos'
    | '/categoria/$categoria'
    | '/negocio/$id'
    | '/pueblo/$pueblo'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cuenta'
    | '/terminos'
    | '/categoria/$categoria'
    | '/negocio/$id'
    | '/pueblo/$pueblo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CuentaRoute: typeof CuentaRoute
  TerminosRoute: typeof TerminosRoute
  CategoriaCategoriaRoute: typeof CategoriaCategoriaRoute
  NegocioIdRoute: typeof NegocioIdRoute
  PuebloPuebloRoute: typeof PuebloPuebloRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuenta': {
      id: '/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof CuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$categoria': {
      id: '/categoria/$categoria'
      path: '/categoria/$categoria'
      fullPath: '/categoria/$categoria'
      preLoaderRoute: typeof CategoriaCategoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negocio/$id': {
      id: '/negocio/$id'
      path: '/negocio/$id'
      fullPath: '/negocio/$id'
      preLoaderRoute: typeof NegocioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pueblo/$pueblo': {
      id: '/pueblo/$pueblo'
      path: '/pueblo/$pueblo'
      fullPath: '/pueblo/$pueblo'
      preLoaderRoute: typeof PuebloPuebloRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CuentaRoute: CuentaRoute,
  TerminosRoute: TerminosRoute,
  CategoriaCategoriaRoute: CategoriaCategoriaRoute,
  NegocioIdRoute: NegocioIdRoute,
  PuebloPuebloRoute: PuebloPuebloRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
